import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },

  admin_cont: {
    width: "80%",
    borderRadius: 1,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 100,
    marginLeft: 40,
    borderRadius: 11,
    backgroundColor: "#2AACAC",
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    textAlignVertical: "center",
  },
  input_button: {
    width: "80%",
    borderRadius: 1,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 90,
    marginLeft: 40,
    borderRadius: 11,
    backgroundColor: "#FFFFFF",
    textAlign: "center",
    textAlignVertical: "center",
  },
  shadow: {
    shadowOffset: { width: 4, height: 4 },
    shadowColor: "#2AACAC",
    shadowOpacity: 20,
    shadowRadius: 2,
    elevation: 5,
  },
  customer_cont: {
    width: "80%",
    borderRadius: 11,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 40,
    marginLeft: 40,
    backgroundColor: "#2AACAC",
    color: "white",
    fontWeight: "bold",
  },
  login_button: {
    width: "30%",
    borderRadius: 11,
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 50,
    //marginLeft: 135,
    alignSelf: "center",
    backgroundColor: "white",
    color: "#2AACAC",
    fontWeight: "bold",
  },
  image: {
    marginBottom: 40,
  },
  otpBoxesContainer: {
    flexDirection: "row",
  },
  otpBox: {
    padding: 10,
    marginRight: 10,
    borderWidth: 1,
    borderColor: "grey",
    height: 45,
    width: 100,
    textAlign: "center",
  },
});
